ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'LOCATION_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'LOCATION_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_DELETED';
